### ISSUE TITLE
Could we implement getSubTimeline to work while providing an element?

### ISSUE THREAD

**Issue by larsvanbraam** [larsvanbraam/vue-transition-component#13]
Could the getSubTimeline work while providing the component element instead of only by providing the id

```javascript
this.viewModel.$refs.items.forEach(item => {
    this.transitionInTimeline.add(this.getSubTimeline(item));
});
```

**Comment by riccomediamonks** [comment]
Think you can match the provided element with the element that is in the child-instance? loop over this.$children -> element === childInstance.element?
