### ISSUE TITLE
Fix convert script for windows machines

### ISSUE THREAD

**Issue by larsvanbraam** [larsvanbraam/vue-transition-component#19]
Currently convert the script does not work on windows machines. It fails running the node-cmd commands. Maybe we can drop this module and run it with https://nodejs.org/api/child_process.html instead.

**Comment by pigeonfresh** [comment]
Not able to test anything at the moment, but perhaps the shell property as an option might be worth to have a look at?
https://github.com/c-h-/node-run-cmd#options-object

**Comment by larsvanbraam** [comment]
@pigeonfresh That seems to work 👍
