### ISSUE TITLE
Need more example

### ISSUE THREAD

**Issue by ksankumar** [larsvanbraam/vue-transition-component#27]
Need example code for all features.
![cross-flow](https://user-images.githubusercontent.com/3350098/52525901-cb4f8b00-2c7e-11e9-9bf8-ac19b6e89cf1.gif)

**Comment by ksankumar** [comment]
For this transition i couldn't find sample implementation code. Please provide how do i implement in real time app

**Comment by larsvanbraam** [comment]
@ksankumar Setting the flow of your page to `FlowType.CROSS` will change the transition order to run simultaneously. Like displayed in the example gif.

```javascript
import { FlowType } from 'vue-transition-component'
...
created() {
  this.flow = FlowType.CROSS
},
...
```

**Comment by ksankumar** [comment]
@larsvanbraam Thanks for came up with code snippet. I tried this code and not working. I don't know what i missed here.

https://codesandbox.io/s/p8yq1lykx

**Comment by larsvanbraam** [comment]
Hey @ksankumar Your codesandbox is missing a lot of required configuration, for a working example please have a look at the [example folder](https://github.com/larsvanbraam/vue-transition-component/tree/master/example) in this repo. Alternatively you can look at this [example online](https://larsvanbraam.github.io/vue-transition-component/example/#/)!

**Comment by ksankumar** [comment]
@larsvanbraam Bro. Thanks again. I followed the same documentation. But in that documentation, we don't have enough code snippet for how do we get FlowType.CROSS page transition. If you don't mind please provide the clear code snippet.

This could be useful to everyone

**Comment by larsvanbraam** [comment]
Hey @ksankumar. I've updated your code sandbox to make it work with the cross flow. I also added some comments so you can see where you were missing stuff. 

Hopefully it helps! 

https://codesandbox.io/s/n5m2zn23o4
